spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rope4job
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 1000
      connection-timeout: 1000
      maximum-pool-size: 3

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
